// Textos del portal del cliente, en español e inglés.
//
// Aparte de src/i18n/translations.ts a propósito: ese archivo trae todos los textos
// de la app del taller, y el cliente solo necesita estos.

export type PortalLanguage = 'es' | 'en';

const es = {
  loading: 'Cargando su reporte…',
  loadError: 'No pudimos cargar el reporte. Revise su conexión e intente de nuevo.',
  retry: 'Intentar de nuevo',
  notFoundTitle: 'Enlace no válido',
  notFoundBody: 'Revise que el enlace esté completo. Si lo copió de un mensaje, puede haberse cortado.',
  revokedTitle: 'Este enlace ya no está activo',
  revokedBody: 'El taller desactivó este enlace. Pídale uno nuevo.',
  expiredTitle: 'Este enlace venció',
  expiredBody: 'Los reportes quedan disponibles 90 días después de la entrega. Si necesita el suyo, comuníquese con el taller.',
  order: 'Orden',
  status: {
    recepcion: 'Recibido',
    en_proceso: 'En proceso',
    espera_autorizacion: 'Esperando su autorización',
    finalizado: 'Listo para recoger',
    entregado: 'Entregado',
  },
  statusHint: {
    recepcion: 'Su vehículo está en el taller y pronto comenzará el trabajo.',
    en_proceso: 'Estamos trabajando en su vehículo.',
    espera_autorizacion: 'Le enviamos un presupuesto. En cuanto lo autorice, seguimos con el trabajo.',
    finalizado: 'El trabajo terminó. Ya puede pasar a recogerlo.',
    entregado: 'Su vehículo fue entregado. Gracias por su confianza.',
  },
  steps: {
    received: 'Recibido',
    working: 'En proceso',
    ready: 'Listo',
    delivered: 'Entregado',
  },
  progress: 'Avance',
  estimatedDelivery: 'Entrega estimada',
  vehicle: 'Vehículo',
  plate: 'Placa',
  noPlate: 'Sin placa',
  vinEnding: 'VIN termina en',
  receptionTitle: 'Recepción del vehículo',
  receivedOn: 'Ingresó',
  mileage: 'Millaje',
  fuel: 'Gasolina',
  receptionNotes: 'Observaciones',
  signature: 'Firma del cliente',
  signedOn: 'Firmado',
  progressTitle: 'Avances del trabajo',
  noProgressMedia: 'Cuando el taller comparta fotos o videos del trabajo, aparecerán aquí.',
  progressNoMessage: 'El taller compartió archivos de este avance.',
  noReceptionMedia: 'Sin fotos de recepción.',
  voiceNote: 'Nota de voz',
  photo: 'Foto',
  video: 'Video',
  close: 'Cerrar',
  previous: 'Anterior',
  next: 'Siguiente',
  mediaExpired: 'Las imágenes caducaron. Actualizando…',
  accountTitle: 'Su cuenta',
  labor: 'Mano de obra',
  parts: 'Repuestos',
  quantityShort: 'Cant.',
  total: 'Total',
  deposit: 'Depósito',
  paid: 'Pagado',
  balance: 'Saldo pendiente',
  paidInFull: 'Pagado en su totalidad',
  noCharges: 'El taller todavía no registró cargos en esta orden.',
  contactTitle: 'Contacto',
  call: 'Llamar',
  whatsapp: 'WhatsApp',
  whatsappMessage: 'Hola, le escribo por la orden {numero}.',
  writeEmail: 'Escribir un correo',
  emailsTitle: 'Avisos por correo',
  emailsOn: 'Le avisamos por correo cuando su vehículo cambia de estado.',
  emailsOff: 'No le enviamos correos sobre esta orden.',
  emailsStop: 'Dejar de recibir correos',
  emailsStart: 'Volver a recibir correos',
  emailsStopConfirm: '¿Quiere dejar de recibir los avisos por correo? Puede volver a activarlos aquí mismo.',
  emailsSaved: 'Preferencia guardada.',
  emailsError: 'No se pudo guardar. Intente de nuevo.',
  unsubscribeHint: 'Llegó desde el enlace de baja del correo. Confirme con el botón:',
  privateLink: 'Este enlace es personal. No lo comparta.',
  expiresOn: 'Disponible hasta el {fecha}.',
  quoteTitle: 'Presupuesto por autorizar',
  quoteIntro: 'El taller preparó este presupuesto. Marque los trabajos que autoriza: solo realizaremos y cobraremos lo que marque.',
  quoteSentOn: 'Enviado el {fecha}',
  selectAll: 'Marcar todo',
  selectNone: 'Desmarcar todo',
  quantityTimes: '{cantidad} × {precio}',
  selectedTotal: 'Total autorizado',
  yourName: 'Su nombre',
  yourNameHint: 'Queda registrado como constancia de su autorización.',
  comment: 'Comentario para el taller (opcional)',
  authorize: 'Autorizar lo marcado',
  rejectAll: 'No autorizar nada',
  confirmAuthorize: '¿Autoriza {count} trabajo(s) por {total}? Lo que no marcó no se realizará.',
  confirmRejectAll: '¿Confirma que no autoriza ningún trabajo de este presupuesto?',
  answered: 'Gracias. Guardamos su respuesta y el taller ya fue avisado.',
  answerErrors: {
    presupuesto_cambio: 'El taller actualizó el presupuesto mientras lo revisaba. Revíselo de nuevo.',
    ya_respondido: 'Este presupuesto ya fue respondido.',
    cancelado: 'El taller retiró este presupuesto.',
    nombre_requerido: 'Escriba su nombre para autorizar.',
    enlace_invalido: 'Este enlace ya no está activo. Comuníquese con el taller.',
    no_encontrado: 'No encontramos este presupuesto. Recargue la página.',
    lineas_invalidas: 'Algo no coincide con el presupuesto. Recargue la página.',
    solicitud_invalida: 'No se pudo enviar la respuesta. Recargue la página.',
    red: 'No se pudo enviar. Revise su conexión e intente de nuevo.',
  } as Record<string, string>,
  notAuthorized: 'No autorizados (no se realizan ni se cobran)',
  historyTitle: 'Sus autorizaciones',
  historyItem: 'Presupuesto {numero} · {via} · {fecha}',
  historyCounts: '{autorizados} autorizado(s), {rechazados} no autorizado(s) · {total}',
  historyBy: 'por {nombre}',
  via: {
    cliente_portal: 'respondido desde este enlace',
    admin_telefono: 'autorizado por teléfono',
    admin_presencial: 'autorizado en el taller',
    admin_whatsapp: 'autorizado por WhatsApp',
    firma_recepcion: 'autorizado con la firma de recepción',
  } as Record<string, string>,
  language: 'English',
  fuelLevels: { E: 'Vacío', '1/4': '1/4', '1/2': '1/2', '3/4': '3/4', F: 'Lleno' } as Record<string, string>,
};

type PortalStrings = typeof es;

const en: PortalStrings = {
  loading: 'Loading your report…',
  loadError: 'We could not load the report. Check your connection and try again.',
  retry: 'Try again',
  notFoundTitle: 'Invalid link',
  notFoundBody: 'Make sure the link is complete. If you copied it from a message, it may have been cut off.',
  revokedTitle: 'This link is no longer active',
  revokedBody: 'The shop turned this link off. Ask them for a new one.',
  expiredTitle: 'This link has expired',
  expiredBody: 'Reports stay available for 90 days after pickup. If you need yours, contact the shop.',
  order: 'Order',
  status: {
    recepcion: 'Checked in',
    en_proceso: 'In progress',
    espera_autorizacion: 'Waiting for your approval',
    finalizado: 'Ready for pickup',
    entregado: 'Picked up',
  },
  statusHint: {
    recepcion: 'Your vehicle is at the shop and work will start soon.',
    en_proceso: 'We are working on your vehicle.',
    espera_autorizacion: 'We sent you an estimate. As soon as you approve it, we continue.',
    finalizado: 'The work is done. You can pick up your vehicle.',
    entregado: 'Your vehicle was picked up. Thank you for your trust.',
  },
  steps: {
    received: 'Checked in',
    working: 'In progress',
    ready: 'Ready',
    delivered: 'Picked up',
  },
  progress: 'Progress',
  estimatedDelivery: 'Estimated completion',
  vehicle: 'Vehicle',
  plate: 'Plate',
  noPlate: 'No plate',
  vinEnding: 'VIN ending in',
  receptionTitle: 'Vehicle check-in',
  receivedOn: 'Checked in',
  mileage: 'Mileage',
  fuel: 'Fuel',
  receptionNotes: 'Notes',
  signature: 'Customer signature',
  signedOn: 'Signed',
  progressTitle: 'Work updates',
  noProgressMedia: 'Photos and videos of the work will appear here when the shop shares them.',
  progressNoMessage: 'The shop shared files for this update.',
  noReceptionMedia: 'No check-in photos.',
  voiceNote: 'Voice note',
  photo: 'Photo',
  video: 'Video',
  close: 'Close',
  previous: 'Previous',
  next: 'Next',
  mediaExpired: 'The images expired. Refreshing…',
  accountTitle: 'Your account',
  labor: 'Labor',
  parts: 'Parts',
  quantityShort: 'Qty',
  total: 'Total',
  deposit: 'Deposit',
  paid: 'Paid',
  balance: 'Balance due',
  paidInFull: 'Paid in full',
  noCharges: 'The shop has not added charges to this order yet.',
  contactTitle: 'Contact',
  call: 'Call',
  whatsapp: 'WhatsApp',
  whatsappMessage: 'Hi, I am writing about order {numero}.',
  writeEmail: 'Send an email',
  emailsTitle: 'Email updates',
  emailsOn: 'We email you when your vehicle changes status.',
  emailsOff: 'We do not send you emails about this order.',
  emailsStop: 'Stop email updates',
  emailsStart: 'Turn email updates back on',
  emailsStopConfirm: 'Stop receiving email updates? You can turn them back on right here.',
  emailsSaved: 'Preference saved.',
  emailsError: 'Could not save. Please try again.',
  unsubscribeHint: 'You came from the unsubscribe link in the email. Confirm with the button:',
  privateLink: 'This link is personal. Do not share it.',
  expiresOn: 'Available until {fecha}.',
  quoteTitle: 'Quote to authorize',
  quoteIntro: 'The shop prepared this quote. Check the work you authorize: we will only do and charge what you check.',
  quoteSentOn: 'Sent on {fecha}',
  selectAll: 'Check all',
  selectNone: 'Uncheck all',
  quantityTimes: '{cantidad} × {precio}',
  selectedTotal: 'Authorized total',
  yourName: 'Your name',
  yourNameHint: 'Recorded as proof of your authorization.',
  comment: 'Comment for the shop (optional)',
  authorize: 'Authorize checked items',
  rejectAll: 'Decline everything',
  confirmAuthorize: 'Authorize {count} item(s) for {total}? Anything unchecked will not be done.',
  confirmRejectAll: 'Confirm that you do not authorize any work in this quote?',
  answered: 'Thank you. We saved your response and the shop has been notified.',
  answerErrors: {
    presupuesto_cambio: 'The shop updated the quote while you were reviewing it. Please review it again.',
    ya_respondido: 'This quote was already answered.',
    cancelado: 'The shop withdrew this quote.',
    nombre_requerido: 'Type your name to authorize.',
    enlace_invalido: 'This link is no longer active. Please contact the shop.',
    no_encontrado: 'We could not find this quote. Reload the page.',
    lineas_invalidas: 'Something does not match the quote. Reload the page.',
    solicitud_invalida: 'The response could not be sent. Reload the page.',
    red: 'Could not send. Check your connection and try again.',
  },
  notAuthorized: 'Not authorized (not done or charged)',
  historyTitle: 'Your authorizations',
  historyItem: 'Quote {numero} · {via} · {fecha}',
  historyCounts: '{autorizados} authorized, {rechazados} declined · {total}',
  historyBy: 'by {nombre}',
  via: {
    cliente_portal: 'answered from this link',
    admin_telefono: 'authorized by phone',
    admin_presencial: 'authorized at the shop',
    admin_whatsapp: 'authorized via WhatsApp',
    firma_recepcion: 'authorized with the check-in signature',
  },
  language: 'Español',
  fuelLevels: { E: 'Empty', '1/4': '1/4', '1/2': '1/2', '3/4': '3/4', F: 'Full' },
};

export const portalStrings: Record<PortalLanguage, PortalStrings> = { es, en };

const STORAGE_KEY = 'restorify_portal_lang';

/** Lo que eligió antes; si no, el idioma del teléfono; español por defecto. */
export function initialPortalLanguage(): PortalLanguage {
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved === 'es' || saved === 'en') return saved;
  } catch {
    // Almacenamiento bloqueado (modo privado de algunos navegadores).
  }
  const nav = typeof navigator !== 'undefined' ? navigator.language || '' : '';
  return /^en\b/i.test(nav) ? 'en' : 'es';
}

export function savePortalLanguage(language: PortalLanguage) {
  try {
    localStorage.setItem(STORAGE_KEY, language);
  } catch {
    // Sin almacenamiento, la elección dura lo que dure la página.
  }
}
