-- ====================================================================================
-- RESTORIFY — Financial integrity around the order lifecycle
-- ====================================================================================
-- Auditing the live data showed the deposit/final-payment automation is correct:
-- income recorded per order matched total_general for delivered orders and the
-- deposit for open ones, with no double counting. Two gaps remained, both of
-- which let the Finanzas module drift away from reality.

-- ------------------------------------------------------------------------------------
-- 1. Editing an order AFTER it was delivered left the money behind.
--    Adding a forgotten part to a delivered order raised total_general but never
--    billed the difference, so the shop silently under-charged. This records the
--    delta as its own movement (income when the job grew, an expense/refund when
--    it shrank), which also keeps an audit trail instead of rewriting history.
-- ------------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_delivered_order_adjustment()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  already_recorded NUMERIC;
  delta NUMERIC;
BEGIN
  -- Only for orders that were already delivered before this update: a fresh
  -- delivery is handled by trg_order_delivery_payment.
  IF OLD.estatus = 'entregado' AND NEW.estatus = 'entregado'
     AND NEW.total_general IS DISTINCT FROM OLD.total_general THEN

    SELECT COALESCE(SUM(CASE WHEN tipo = 'ingreso' THEN monto ELSE -monto END), 0)
    INTO already_recorded
    FROM finanzas_movimientos
    WHERE referencia_orden_id = NEW.id AND categoria = 'pago_cliente';

    delta := NEW.total_general - already_recorded;

    IF ABS(delta) > 0.01 THEN
      INSERT INTO finanzas_movimientos (
        sede_id, tipo, categoria, monto, descripcion, fecha, referencia_orden_id
      )
      VALUES (
        NEW.sede_id,
        CASE WHEN delta > 0 THEN 'ingreso' ELSE 'egreso' END,
        'pago_cliente',
        ABS(delta),
        CASE WHEN delta > 0 THEN 'Ajuste por cargo adicional - ' ELSE 'Reembolso por ajuste - ' END
          || NEW.numero_orden,
        CURRENT_DATE,
        NEW.id
      );
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_delivered_order_adjustment ON ordenes_trabajo;
CREATE TRIGGER trg_delivered_order_adjustment
  AFTER UPDATE ON ordenes_trabajo
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_delivered_order_adjustment();

-- ------------------------------------------------------------------------------------
-- 2. Deleting an order orphaned its money.
--    finanzas_movimientos.referencia_orden_id is ON DELETE SET NULL, so removing
--    a mistakenly created order left its deposit counted as income forever with
--    no way to trace it back. Movements generated by the order automation are
--    removed with the order; anything reconciled from a bank statement is kept,
--    because that money really did move through the account.
-- ------------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.cleanup_order_finance()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  DELETE FROM finanzas_movimientos
  WHERE referencia_orden_id = OLD.id
    AND importacion_id IS NULL;
  RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS trg_cleanup_order_finance ON ordenes_trabajo;
CREATE TRIGGER trg_cleanup_order_finance
  BEFORE DELETE ON ordenes_trabajo
  FOR EACH ROW
  EXECUTE FUNCTION public.cleanup_order_finance();

-- ------------------------------------------------------------------------------------
-- 3. Reporting index: the audit above scanned every movement to group them by
--    order. Finanzas and the order detail both do that lookup.
-- ------------------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_finanzas_movimientos_orden
  ON finanzas_movimientos (referencia_orden_id)
  WHERE referencia_orden_id IS NOT NULL;
